apiVersion: apps/v1
kind: Deployment
metadata:
  name: virement-service
  namespace: banking-microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: virement-service
  template:
    metadata:
      labels:
        app: virement-service
    spec:
      containers:
      - name: virement-service
        image: virement-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8082
        env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://discovery-service:8761/eureka/"
---
apiVersion: v1
kind: Service
metadata:
  name: virement-service
  namespace: banking-microservices
spec:
  type: ClusterIP
  ports:
  - port: 8082
    targetPort: 8082
  selector:
    app: virement-service
